/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserAgreementRouteImport } from './routes/user-agreement'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportIssueRouteImport } from './routes/report-issue'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MockTestsRouteImport } from './routes/mock-tests'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpSupportRouteImport } from './routes/help-support'
import { Route as FeeCalculatorRouteImport } from './routes/fee-calculator'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DrivingGuideRouteImport } from './routes/driving-guide'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DataProtectionRouteImport } from './routes/data-protection'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CourseRouteImport } from './routes/course'
import { Route as CopyrightRouteImport } from './routes/copyright'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthErrorRouteImport } from './routes/auth-error'
import { Route as ApplicationTrackingRouteImport } from './routes/application-tracking'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AcceptableUseRouteImport } from './routes/acceptable-use'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizIndexRouteImport } from './routes/quiz.index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as QuizSetIdRouteImport } from './routes/quiz.$setId'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as ApiPublicAiHealthRouteImport } from './routes/api/public/ai-health'

const UserAgreementRoute = UserAgreementRouteImport.update({
  id: '/user-agreement',
  path: '/user-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIssueRoute = ReportIssueRouteImport.update({
  id: '/report-issue',
  path: '/report-issue',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestsRoute = MockTestsRouteImport.update({
  id: '/mock-tests',
  path: '/mock-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpSupportRoute = HelpSupportRouteImport.update({
  id: '/help-support',
  path: '/help-support',
  getParentRoute: () => rootRouteImport,
} as any)
const FeeCalculatorRoute = FeeCalculatorRouteImport.update({
  id: '/fee-calculator',
  path: '/fee-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DrivingGuideRoute = DrivingGuideRouteImport.update({
  id: '/driving-guide',
  path: '/driving-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DataProtectionRoute = DataProtectionRouteImport.update({
  id: '/data-protection',
  path: '/data-protection',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightRoute = CopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth-error',
  path: '/auth-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationTrackingRoute = ApplicationTrackingRouteImport.update({
  id: '/application-tracking',
  path: '/application-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUseRoute = AcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSetIdRoute = QuizSetIdRouteImport.update({
  id: '/quiz/$setId',
  path: '/quiz/$setId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicAiHealthRoute = ApiPublicAiHealthRouteImport.update({
  id: '/api/public/ai-health',
  path: '/api/public/ai-health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/application-tracking': typeof ApplicationTrackingRoute
  '/auth-error': typeof AuthErrorRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/copyright': typeof CopyrightRoute
  '/course': typeof CourseRoute
  '/dashboard': typeof DashboardRoute
  '/data-protection': typeof DataProtectionRoute
  '/disclaimer': typeof DisclaimerRoute
  '/driving-guide': typeof DrivingGuideRoute
  '/faq': typeof FaqRoute
  '/fee-calculator': typeof FeeCalculatorRoute
  '/help-support': typeof HelpSupportRoute
  '/login': typeof LoginRoute
  '/mock-tests': typeof MockTestsRoute
  '/privacy': typeof PrivacyRoute
  '/report-issue': typeof ReportIssueRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/user-agreement': typeof UserAgreementRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/category/$slug': typeof CategorySlugRoute
  '/quiz/$setId': typeof QuizSetIdRoute
  '/auth/': typeof AuthIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/api/public/ai-health': typeof ApiPublicAiHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/application-tracking': typeof ApplicationTrackingRoute
  '/auth-error': typeof AuthErrorRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/copyright': typeof CopyrightRoute
  '/course': typeof CourseRoute
  '/dashboard': typeof DashboardRoute
  '/data-protection': typeof DataProtectionRoute
  '/disclaimer': typeof DisclaimerRoute
  '/driving-guide': typeof DrivingGuideRoute
  '/faq': typeof FaqRoute
  '/fee-calculator': typeof FeeCalculatorRoute
  '/help-support': typeof HelpSupportRoute
  '/login': typeof LoginRoute
  '/mock-tests': typeof MockTestsRoute
  '/privacy': typeof PrivacyRoute
  '/report-issue': typeof ReportIssueRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/user-agreement': typeof UserAgreementRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/category/$slug': typeof CategorySlugRoute
  '/quiz/$setId': typeof QuizSetIdRoute
  '/auth': typeof AuthIndexRoute
  '/quiz': typeof QuizIndexRoute
  '/api/public/ai-health': typeof ApiPublicAiHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/application-tracking': typeof ApplicationTrackingRoute
  '/auth-error': typeof AuthErrorRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/copyright': typeof CopyrightRoute
  '/course': typeof CourseRoute
  '/dashboard': typeof DashboardRoute
  '/data-protection': typeof DataProtectionRoute
  '/disclaimer': typeof DisclaimerRoute
  '/driving-guide': typeof DrivingGuideRoute
  '/faq': typeof FaqRoute
  '/fee-calculator': typeof FeeCalculatorRoute
  '/help-support': typeof HelpSupportRoute
  '/login': typeof LoginRoute
  '/mock-tests': typeof MockTestsRoute
  '/privacy': typeof PrivacyRoute
  '/report-issue': typeof ReportIssueRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/user-agreement': typeof UserAgreementRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/category/$slug': typeof CategorySlugRoute
  '/quiz/$setId': typeof QuizSetIdRoute
  '/auth/': typeof AuthIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/api/public/ai-health': typeof ApiPublicAiHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/acceptable-use'
    | '/ai-assistant'
    | '/application-tracking'
    | '/auth-error'
    | '/contact'
    | '/cookie-policy'
    | '/copyright'
    | '/course'
    | '/dashboard'
    | '/data-protection'
    | '/disclaimer'
    | '/driving-guide'
    | '/faq'
    | '/fee-calculator'
    | '/help-support'
    | '/login'
    | '/mock-tests'
    | '/privacy'
    | '/report-issue'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/trust'
    | '/user-agreement'
    | '/profile'
    | '/api/chat'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/category/$slug'
    | '/quiz/$setId'
    | '/auth/'
    | '/quiz/'
    | '/api/public/ai-health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/acceptable-use'
    | '/ai-assistant'
    | '/application-tracking'
    | '/auth-error'
    | '/contact'
    | '/cookie-policy'
    | '/copyright'
    | '/course'
    | '/dashboard'
    | '/data-protection'
    | '/disclaimer'
    | '/driving-guide'
    | '/faq'
    | '/fee-calculator'
    | '/help-support'
    | '/login'
    | '/mock-tests'
    | '/privacy'
    | '/report-issue'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/trust'
    | '/user-agreement'
    | '/profile'
    | '/api/chat'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/category/$slug'
    | '/quiz/$setId'
    | '/auth'
    | '/quiz'
    | '/api/public/ai-health'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/acceptable-use'
    | '/ai-assistant'
    | '/application-tracking'
    | '/auth-error'
    | '/contact'
    | '/cookie-policy'
    | '/copyright'
    | '/course'
    | '/dashboard'
    | '/data-protection'
    | '/disclaimer'
    | '/driving-guide'
    | '/faq'
    | '/fee-calculator'
    | '/help-support'
    | '/login'
    | '/mock-tests'
    | '/privacy'
    | '/report-issue'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/trust'
    | '/user-agreement'
    | '/_authenticated/profile'
    | '/api/chat'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/category/$slug'
    | '/quiz/$setId'
    | '/auth/'
    | '/quiz/'
    | '/api/public/ai-health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcceptableUseRoute: typeof AcceptableUseRoute
  AiAssistantRoute: typeof AiAssistantRoute
  ApplicationTrackingRoute: typeof ApplicationTrackingRoute
  AuthErrorRoute: typeof AuthErrorRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  CopyrightRoute: typeof CopyrightRoute
  CourseRoute: typeof CourseRoute
  DashboardRoute: typeof DashboardRoute
  DataProtectionRoute: typeof DataProtectionRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DrivingGuideRoute: typeof DrivingGuideRoute
  FaqRoute: typeof FaqRoute
  FeeCalculatorRoute: typeof FeeCalculatorRoute
  HelpSupportRoute: typeof HelpSupportRoute
  LoginRoute: typeof LoginRoute
  MockTestsRoute: typeof MockTestsRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportIssueRoute: typeof ReportIssueRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  UserAgreementRoute: typeof UserAgreementRoute
  ApiChatRoute: typeof ApiChatRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  CategorySlugRoute: typeof CategorySlugRoute
  QuizSetIdRoute: typeof QuizSetIdRoute
  AuthIndexRoute: typeof AuthIndexRoute
  QuizIndexRoute: typeof QuizIndexRoute
  ApiPublicAiHealthRoute: typeof ApiPublicAiHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-agreement': {
      id: '/user-agreement'
      path: '/user-agreement'
      fullPath: '/user-agreement'
      preLoaderRoute: typeof UserAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-issue': {
      id: '/report-issue'
      path: '/report-issue'
      fullPath: '/report-issue'
      preLoaderRoute: typeof ReportIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-tests': {
      id: '/mock-tests'
      path: '/mock-tests'
      fullPath: '/mock-tests'
      preLoaderRoute: typeof MockTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-support': {
      id: '/help-support'
      path: '/help-support'
      fullPath: '/help-support'
      preLoaderRoute: typeof HelpSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fee-calculator': {
      id: '/fee-calculator'
      path: '/fee-calculator'
      fullPath: '/fee-calculator'
      preLoaderRoute: typeof FeeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driving-guide': {
      id: '/driving-guide'
      path: '/driving-guide'
      fullPath: '/driving-guide'
      preLoaderRoute: typeof DrivingGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-protection': {
      id: '/data-protection'
      path: '/data-protection'
      fullPath: '/data-protection'
      preLoaderRoute: typeof DataProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright': {
      id: '/copyright'
      path: '/copyright'
      fullPath: '/copyright'
      preLoaderRoute: typeof CopyrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-error': {
      id: '/auth-error'
      path: '/auth-error'
      fullPath: '/auth-error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-tracking': {
      id: '/application-tracking'
      path: '/application-tracking'
      fullPath: '/application-tracking'
      preLoaderRoute: typeof ApplicationTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use': {
      id: '/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/acceptable-use'
      preLoaderRoute: typeof AcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$setId': {
      id: '/quiz/$setId'
      path: '/quiz/$setId'
      fullPath: '/quiz/$setId'
      preLoaderRoute: typeof QuizSetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/ai-health': {
      id: '/api/public/ai-health'
      path: '/api/public/ai-health'
      fullPath: '/api/public/ai-health'
      preLoaderRoute: typeof ApiPublicAiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AcceptableUseRoute: AcceptableUseRoute,
  AiAssistantRoute: AiAssistantRoute,
  ApplicationTrackingRoute: ApplicationTrackingRoute,
  AuthErrorRoute: AuthErrorRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  CopyrightRoute: CopyrightRoute,
  CourseRoute: CourseRoute,
  DashboardRoute: DashboardRoute,
  DataProtectionRoute: DataProtectionRoute,
  DisclaimerRoute: DisclaimerRoute,
  DrivingGuideRoute: DrivingGuideRoute,
  FaqRoute: FaqRoute,
  FeeCalculatorRoute: FeeCalculatorRoute,
  HelpSupportRoute: HelpSupportRoute,
  LoginRoute: LoginRoute,
  MockTestsRoute: MockTestsRoute,
  PrivacyRoute: PrivacyRoute,
  ReportIssueRoute: ReportIssueRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  UserAgreementRoute: UserAgreementRoute,
  ApiChatRoute: ApiChatRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  CategorySlugRoute: CategorySlugRoute,
  QuizSetIdRoute: QuizSetIdRoute,
  AuthIndexRoute: AuthIndexRoute,
  QuizIndexRoute: QuizIndexRoute,
  ApiPublicAiHealthRoute: ApiPublicAiHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
