// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function normalizeSupabaseUrl(value: string) {
  return value.trim().replace(/\/+$/, "");
}

function createSupabaseClient() {
  const rawUrl = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const anonKey =
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_ANON_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY;

  const missing = [
    ...(!rawUrl ? ["VITE_SUPABASE_URL"] : []),
    ...(!anonKey ? ["VITE_SUPABASE_ANON_KEY"] : []),
  ];

  if (missing.length > 0) {
    const message = `Missing Supabase environment variable(s): ${missing.join(
      ", ",
    )}. Add the public Supabase URL and anon key in Vercel/Lovable.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const supabaseUrl = normalizeSupabaseUrl(rawUrl);

  if (supabaseUrl.includes("/rest/v1")) {
    throw new Error(
      "VITE_SUPABASE_URL must be the project URL (for example https://apciavkljjnjysgmwmkk.supabase.co), not the REST endpoint.",
    );
  }

  return createClient<Database>(supabaseUrl, anonKey, {
    auth: {
      storage: typeof window !== "undefined" ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: "pkce",
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
